<a href="https://colab.research.google.com/github/BhoomiMahna/TripSense/blob/data/tripsensedata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving travel_data.csv to travel_data.csv

In [ ]:
import pandas as pd
df=pd.read_csv('travel_data.csv')
df.head(30)

,RowID,CustomerID,Age,Gender,Destination,Category,State,District,Latitude,Longitude,...,NatureScore,CultureScore,AdventureScore,SpiritualScore,BookingLeadDays,DurationDays,FamilySize,InternetSpeedMbps,NetworkQuality,PermitsRequired
0,1,CUST_001,35,Female,Munnar,Hill Station,Kerala,Idukki,10.08,77.05,...,9,6,4,3,1,10,1,80,NaN,No
1,2,CUST_001,35,Female,Goa,Beach,Goa,North Goa,15.29,74.12,...,3,1,5,7,365,5,4,10,Poor,No
2,3,CUST_001,35,Female,Tawang,Mountain,Arunachal Pradesh,Tawang,27.58,91.86,...,9,7,6,9,1,3,10,1000,Poor,No
3,4,CUST_002,150,Female,Shillong,Nature,Meghalaya,East Khasi,25.57,91.88,...,10,2,6,1,60,4,4,20,NaN,YES
4,5,CUST_002,150,Female,Delhi,Urban,Delhi,New Delhi,28.61,77.20,...,7,8,1,1,7,14,2,1000,Poor,No
5,6,CUST_002,150,Female,Tawang,Mountain,Arunachal Pradesh,Tawang,27.58,91.86,...,9,6,2,2,120,1,5,5,Excellent,Yes
6,7,CUST_002,150,Female,Shillong,Nature,Meghalaya,East Khasi,25.57,91.88,...,6,1,3,7,3,3,3,150,Moderate,YES
7,8,CUST_002,150,Female,Goa,Beach,Goa,North Goa,15.29,74.12,...,3,9,6,9,3,3,5,80,Excellent,No
8,9,CUST_002,150,Female,Manali,Hill Station,Himachal Pradesh,Kullu,32.24,77.19,...,1,3,9,6,2000,45,5,150,Moderate,No
9,10,CUST_002,150,Female,Shillong,Nature,Meghalaya,East Khasi,25.57,91.88,...,6,5,7,1,2000,2,2,20,NaN,Yes
10,11,CUST_003,150,FEMALE,Leh,Adventure,Ladakh,Leh,34.15,77.57,...,8,7,1,5,365,7,4,1000,Moderate,YES
11,12,CUST_003,150,FEMALE,Varanasi,Spiritual,Uttar Pradesh,Varanasi,25.31,82.97,...,8,6,7,6,60,4,4,80,Good,Yes
12,13,CUST_003,150,FEMALE,Varanasi,Spiritual,Uttar Pradesh,Varanasi,25.31,82.97,...,2,5,2,5,2000,7,1,80,Excellent,Yes
13,14,CUST_004,37,Female,Udaipur,Heritage,Rajasthan,Udaipur,24.58,73.68,...,4,8,9,10,30,7,1,80,Moderate,Yes
14,15,CUST_004,37,Female,Manali,Hill Station,Himachal Pradesh,Kullu,32.24,77.19,...,6,6,4,10,1,14,5,10,NaN,No
15,16,CUST_004,37,Female,Delhi,Urban,Delhi,New Delhi,28.61,77.20,...,3,7,6,7,1,1,4,40,Moderate,Yes
16,17,CUST_004,37,Female,Manali,Hill Station,Himachal Pradesh,Kullu,32.24,77.19,...,8,4,5,9,3,2,4,1000,NaN,YES
17,18,CUST_004,37,Female,Shillong,Nature,Meghalaya,East Khasi,25.57,91.88,...,2,1,10,7,120,45,3,1000,Moderate,No
18,19,CUST_004,37,Female,Varanasi,Spiritual,Uttar Pradesh,Varanasi,25.31,82.97,...,1,1,7,6,2000,1,1,150,Moderate,YES
19,20,CUST_004,37,Female,Hampi,Heritage,Karnataka,Ballari,15.33,76.46,...,9,1,6,3,365,4,4,20,Moderate,YES
20,21,CUST_004,37,Female,Mumbai,Urban,Maharashtra,Mumbai,19.07,72.87,...,3,8,2,3,3,14,3,40,NaN,YES
21,22,CUST_004,37,Female,Manali,Hill Station,Himachal Pradesh,Kullu,32.24,77.19,...,10,6,2,4,120,3,4,5,Moderate,No
22,23,CUST_005,18,Male,Tawang,Mountain,Arunachal Pradesh,Tawang,27.58,91.86,...,1,3,2,8,3,3,10,0,Poor,No
23,24,CUST_005,18,Male,Puri,Beach,Odisha,Puri,19.81,85.83,...,5,6,7,6,15,1,1,0,NaN,Yes
24,25,CUST_005,18,Male,Goa,Beach,Goa,North Goa,15.29,74.12,...,9,6,6,3,120,1,5,150,Good,No
25,26,CUST_005,18,Male,Tawang,Mountain,Arunachal Pradesh,Tawang,27.58,91.86,...,10,6,8,2,2000,4,4,10,Poor,Yes
26,27,CUST_005,18,Male,Leh,Adventure,Ladakh,Leh,34.15,77.57,...,1,5,1,3,15,7,2,150,Poor,Yes
27,28,CUST_006,35,Male,Tawang,Mountain,Arunachal Pradesh,Tawang,27.58,91.86,...,9,2,6,5,30,14,2,5,Poor,Yes
28,29,CUST_006,35,Male,Goa,Beach,Goa,North Goa,15.29,74.12,...,1,7,4,4,1,10,2,150,Poor,Yes
29,30,CUST_006,35,Male,Shillong,Nature,Meghalaya,East Khasi,25.57,91.88,...,1,2,10,7,30,1,10,5,NaN,YES

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189 entries, 0 to 188
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RowID              189 non-null    int64
 1   CustomerID         189 non-null    object
 2   Age                189 non-null    int64
 3   Gender             189 non-null    object
 4   Destination        189 non-null    object
 5   Category           189 non-null    object
 6   State              189 non-null    object
 7   District           189 non-null    object
 8   Latitude           189 non-null    float64
 9   Longitude          189 non-null    float64
 10  ModeOfTransport    189 non-null    object
 11  TravelCostINR      149 non-null    float64
 12  BudgetPerDayINR    189 non-null    int64
 13  MidrangePerDayINR  189 non-null    int64
 14  LuxuryPerDayINR    189 non-null    int64
 15  NatureScore        189 non-null    int64
 16  CultureScore       189 non-null    int64
 17  AdventureScore     189 non-null    int64
 18  SpiritualScore     189 non-null    int64
 19  BookingLeadDays    189 non-null    int64
 20  DurationDays       189 non-null    int64
 21  FamilySize         189 non-null    int64
 22  InternetSpeedMbps  189 non-null    int64
 23  NetworkQuality     151 non-null    object
 24  PermitsRequired    189 non-null    object
dtypes: float64(3), int64(13), object(9)
memory usage: 37.0+ KB

In [ ]:
df.isnull().sum()
df.describe()

,RowID,Age,Latitude,Longitude,TravelCostINR,BudgetPerDayINR,MidrangePerDayINR,LuxuryPerDayINR,NatureScore,CultureScore,AdventureScore,SpiritualScore,BookingLeadDays,DurationDays,FamilySize,InternetSpeedMbps
count,189.000000,189.000000,189.000000,189.000000,149.000000,189.000000,189.000000,189.000000,189.000000,189.000000,189.00000,189.000000,189.000000,189.000000,189.000000,189.000000
mean,95.000000,48.656085,23.496190,79.968836,34127.651007,671.132275,4056.206349,285657.439153,5.190476,5.349206,5.15873,5.222222,282.529101,9.306878,4.195767,211.640212
std,54.703748,58.807143,6.922515,6.625667,46936.039577,1860.525889,2489.857181,225915.056852,2.943748,2.781925,2.78602,2.819637,603.623593,11.660581,2.882224,366.553395
min,1.000000,-5.000000,10.080000,72.870000,-2000.000000,-1000.000000,1003.000000,7497.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,48.000000,-5.000000,19.070000,74.120000,2603.000000,-1000.000000,2125.000000,54330.000000,3.000000,3.000000,3.00000,3.000000,3.000000,3.000000,2.000000,5.000000
50%,95.000000,36.000000,25.310000,77.200000,12689.000000,0.000000,3331.000000,500000.000000,5.000000,5.000000,5.00000,5.000000,30.000000,5.000000,4.000000,40.000000
75%,142.000000,64.000000,28.610000,85.830000,25000.000000,1946.000000,6112.000000,500000.000000,8.000000,8.000000,7.00000,8.000000,120.000000,10.000000,5.000000,150.000000
max,189.000000,150.000000,34.150000,91.880000,120000.000000,4928.000000,10331.000000,500000.000000,10.000000,10.000000,10.00000,10.000000,2000.000000,45.000000,10.000000,1000.000000

In [ ]:
df.isnull().sum()

RowID                 0
CustomerID            0
Age                   0
Gender                0
Destination           0
Category              0
State                 0
District              0
Latitude              0
Longitude             0
ModeOfTransport       0
TravelCostINR        40
BudgetPerDayINR       0
MidrangePerDayINR     0
LuxuryPerDayINR       0
NatureScore           0
CultureScore          0
AdventureScore        0
SpiritualScore        0
BookingLeadDays       0
DurationDays          0
FamilySize            0
InternetSpeedMbps     0
NetworkQuality       38
PermitsRequired       0
dtype: int64

In [ ]:
df['TravelCostINR']=df['TravelCostINR'].fillna(df['TravelCostINR'].median())

if not df['NetworkQuality'].mode().empty:
      df['NetworkQuality']=df['NetworkQuality'].fillna(df['NetworkQuality'].mode()[0])
else:
     df['NetworkQuality'] = df['NetworkQuality'].fillna('Unknown')

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
numeric_cols=df.select_dtypes(include='number').columns
negatives=df[numeric_cols]<0
neg_counts=negatives.sum()
neg_counts[neg_counts>0]

Age                69
TravelCostINR      28
BudgetPerDayINR    62
dtype: int64

In [ ]:
df[numeric_cols]=df[numeric_cols].abs()

In [ ]:
df.head()

,RowID,CustomerID,Age,Gender,Destination,Category,State,District,Latitude,Longitude,...,NatureScore,CultureScore,AdventureScore,SpiritualScore,BookingLeadDays,DurationDays,FamilySize,InternetSpeedMbps,NetworkQuality,PermitsRequired
0,1,CUST_001,35,Female,Munnar,Hill Station,Kerala,Idukki,10.08,77.05,...,9,6,4,3,1,10,1,80,Unknown,No
1,2,CUST_001,35,Female,Goa,Beach,Goa,North Goa,15.29,74.12,...,3,1,5,7,365,5,4,10,Unknown,No
2,3,CUST_001,35,Female,Tawang,Mountain,Arunachal Pradesh,Tawang,27.58,91.86,...,9,7,6,9,1,3,10,1000,Unknown,No
3,4,CUST_002,150,Female,Shillong,Nature,Meghalaya,East Khasi,25.57,91.88,...,10,2,6,1,60,4,4,20,Unknown,YES
4,5,CUST_002,150,Female,Delhi,Urban,Delhi,New Delhi,28.61,77.20,...,7,8,1,1,7,14,2,1000,Unknown,No

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in ['Gender','Destination','Category','State','District','NetworkQuality','PermitsRequired']:
  df[col]=le.fit_transform(df[col])

In [ ]:
df.head()

,RowID,CustomerID,Age,Gender,Destination,Category,State,District,Latitude,Longitude,...,NatureScore,CultureScore,AdventureScore,SpiritualScore,BookingLeadDays,DurationDays,FamilySize,InternetSpeedMbps,NetworkQuality,PermitsRequired
0,1,CUST_001,35,1,6,3,5,2,10.08,77.05,...,9,6,4,3,1,10,1,80,0,0
1,2,CUST_001,35,1,1,1,2,7,15.29,74.12,...,3,1,5,7,365,5,4,10,0,0
2,3,CUST_001,35,1,9,4,0,9,27.58,91.86,...,9,7,6,9,1,3,10,1000,0,0
3,4,CUST_002,150,1,8,5,8,1,25.57,91.88,...,10,2,6,1,60,4,4,20,0,1
4,5,CUST_002,150,1,0,7,1,6,28.61,77.20,...,7,8,1,1,7,14,2,1000,0,0

In [ ]:
df.isnull().sum()

RowID                0
CustomerID           0
Age                  0
Gender               0
Destination          0
Category             0
State                0
District             0
Latitude             0
Longitude            0
ModeOfTransport      0
TravelCostINR        0
BudgetPerDayINR      0
MidrangePerDayINR    0
LuxuryPerDayINR      0
NatureScore          0
CultureScore         0
AdventureScore       0
SpiritualScore       0
BookingLeadDays      0
DurationDays         0
FamilySize           0
InternetSpeedMbps    0
NetworkQuality       0
PermitsRequired      0
dtype: int64

In [ ]:
trip_freq=df.groupby('CustomerID').size().reset_index(name='trip_frequency_per_year')

In [ ]:
customer_agg = df.groupby('CustomerID').agg({
    'Age':'first',
    'Gender':'first',
    'NatureScore':'mean',
    'CultureScore':'mean',
    'AdventureScore':'mean',
    'SpiritualScore':'mean',
    'BookingLeadDays':'mean',
    'DurationDays':'mean',
    'FamilySize':'mean',
    'InternetSpeedMbps':'mean',
    'NetworkQuality':'mean',
    'PermitsRequired':'mean',
    'Destination':'nunique',
    'Category':'nunique'
}).reset_index()


customer_agg.rename(columns={'Destination':'destination_diversity','Category':'category_diversity'}, inplace=True)

In [ ]:

customer_agg = customer_agg.merge(trip_freq, on='CustomerID', how='left')

customer_agg.head()

,CustomerID,Age,Gender,NatureScore,CultureScore,AdventureScore,SpiritualScore,BookingLeadDays,DurationDays,FamilySize,InternetSpeedMbps,NetworkQuality,PermitsRequired,destination_diversity,category_diversity,trip_frequency_per_year
0,CUST_001,35,1,7.000000,4.666667,5.000000,6.333333,122.333333,6.000000,5.000000,363.333333,2.666667,0.000000,3,3,3
1,CUST_002,150,1,6.000000,4.857143,4.857143,3.857143,599.000000,10.285714,3.714286,203.571429,1.571429,0.857143,5,5,7
2,CUST_003,150,0,6.000000,6.000000,3.333333,5.333333,808.333333,6.000000,3.000000,386.666667,1.000000,1.666667,2,2,3
3,CUST_004,37,1,5.111111,4.666667,5.666667,6.555556,293.666667,10.111111,3.222222,260.555556,2.000000,0.888889,7,5,9
4,CUST_005,18,2,5.200000,5.200000,4.800000,4.400000,430.600000,3.200000,4.400000,62.000000,2.400000,1.200000,4,3,5

In [ ]:
print(customer_agg.columns.tolist())

['CustomerID', 'Age', 'Gender', 'NatureScore', 'CultureScore', 'AdventureScore', 'SpiritualScore', 'BookingLeadDays', 'DurationDays', 'FamilySize', 'InternetSpeedMbps', 'NetworkQuality', 'PermitsRequired', 'destination_diversity', 'category_diversity', 'trip_frequency_per_year']

these features can be used ofr clustering so making them

In [ ]:

customer_agg['adventure_pref_score'] = customer_agg['AdventureScore'] * customer_agg['DurationDays']
customer_agg['culture_pref_score'] = customer_agg['CultureScore'] * customer_agg['BookingLeadDays']
customer_agg['nature_pref_score'] = customer_agg['NatureScore'] * customer_agg['DurationDays']
customer_agg['spiritual_pref_score'] = customer_agg['SpiritualScore'] * customer_agg['DurationDays']
customer_agg['engagement_score'] = customer_agg['destination_diversity'] * customer_agg['DurationDays']
customer_agg['avg_booking_value_inr'] = (
    customer_agg['DurationDays'] * 3000 * customer_agg['FamilySize']
)
customer_agg['international_trip_ratio'] = (
    (customer_agg['PermitsRequired'] == 1).astype(int)
)
customer_agg['luxury_hotel_ratio'] = (
    (customer_agg['NatureScore'] +
     customer_agg['CultureScore'] +
     customer_agg['SpiritualScore']) / 30
)
customer_agg['budget_booking_ratio'] = (
    customer_agg['AdventureScore'] / 10
)
customer_agg['price_sensitivity_score'] = (
    customer_agg['FamilySize'] / (customer_agg['BookingLeadDays'] + 1)
)
customer_agg['weekend_trip_ratio'] = (
    (customer_agg['DurationDays'] <= 3).astype(int)
)
customer_agg['last_minute_search_ratio'] = (
    (customer_agg['BookingLeadDays'] <= 5).astype(int)
)
customer_agg['cancellation_rate'] = (
    1 / (customer_agg['engagement_score'] + 1)
)
customer_agg['loyalty_points_balance'] = (
    customer_agg['trip_frequency_per_year'] *
    customer_agg['engagement_score'] * 10
)
customer_agg['mobile_booking_ratio'] = (
    customer_agg['InternetSpeedMbps'] / 100
)

In [ ]:
customer_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CustomerID                30 non-null     object
 1   Age                       30 non-null     float64
 2   Gender                    30 non-null     int64
 3   NatureScore               30 non-null     float64
 4   CultureScore              30 non-null     float64
 5   AdventureScore            30 non-null     float64
 6   SpiritualScore            30 non-null     float64
 7   BookingLeadDays           30 non-null     float64
 8   DurationDays              30 non-null     float64
 9   FamilySize                30 non-null     float64
 10  InternetSpeedMbps         30 non-null     float64
 11  NetworkQuality            30 non-null     float64
 12  PermitsRequired           30 non-null     float64
 13  destination_diversity     30 non-null     float64
 14  category_diversity        30 non-null     float64
 15  trip_frequency_per_year   30 non-null     int64
 16  adventure_pref_score      30 non-null     float64
 17  culture_pref_score        30 non-null     float64
 18  nature_pref_score         30 non-null     float64
 19  spiritual_pref_score      30 non-null     float64
 20  engagement_score          30 non-null     float64
 21  target_booking            30 non-null     int64
 22  target_response           30 non-null     int64
 23  avg_booking_value_inr     30 non-null     float64
 24  international_trip_ratio  30 non-null     int64
 25  luxury_hotel_ratio        30 non-null     float64
 26  budget_booking_ratio      30 non-null     float64
 27  price_sensitivity_score   30 non-null     float64
 28  weekend_trip_ratio        30 non-null     int64
 29  last_minute_search_ratio  30 non-null     int64
 30  cancellation_rate         30 non-null     float64
 31  loyalty_points_balance    30 non-null     float64
 32  mobile_booking_ratio      30 non-null     float64
dtypes: float64(25), int64(7), object(1)
memory usage: 7.9+ KB

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

numeric = [
    'Age',
    'Gender',
    'NatureScore',
    'CultureScore',
    'AdventureScore',
    'SpiritualScore',
    'BookingLeadDays',
    'DurationDays',
    'FamilySize',
    'InternetSpeedMbps',
    'NetworkQuality',
    'PermitsRequired',
    'destination_diversity',
    'category_diversity',
    'trip_frequency_per_year',
    'adventure_pref_score',
    'culture_pref_score',
    'nature_pref_score',
    'spiritual_pref_score',
    'engagement_score',
    'avg_booking_value_inr',
    'international_trip_ratio',
    'luxury_hotel_ratio',
    'budget_booking_ratio',
    'price_sensitivity_score',
    'weekend_trip_ratio',
    'last_minute_search_ratio',
    'cancellation_rate',
    'loyalty_points_balance',
    'mobile_booking_ratio'
]

customer_agg[numeric]=scaler.fit_transform(customer_agg[numeric])

In [ ]:
customer_agg.describe()

,Age,Gender,NatureScore,CultureScore,AdventureScore,SpiritualScore,BookingLeadDays,DurationDays,FamilySize,InternetSpeedMbps,...,avg_booking_value_inr,international_trip_ratio,luxury_hotel_ratio,budget_booking_ratio,price_sensitivity_score,weekend_trip_ratio,last_minute_search_ratio,cancellation_rate,loyalty_points_balance,mobile_booking_ratio
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.0,30.0,30.000000,30.000000,30.000000
mean,0.353793,0.450000,0.468365,0.451214,0.410347,0.582718,0.237128,0.265149,0.455837,0.342363,...,0.180445,0.033333,0.534344,0.410347,0.435831,0.0,0.0,0.682644,0.188927,0.342363
std,0.386089,0.422431,0.262587,0.255834,0.232711,0.231267,0.225567,0.234662,0.266324,0.252111,...,0.245217,0.182574,0.259380,0.232711,0.264880,0.0,0.0,0.274004,0.226414,0.252111
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.312016,0.283333,0.299107,0.451970,0.055244,0.102882,0.278963,0.113943,...,0.037692,0.000000,0.365643,0.299107,0.266254,0.0,0.0,0.453785,0.045833,0.113943
50%,0.217241,0.500000,0.454780,0.408889,0.425893,0.566502,0.203132,0.150398,0.402439,0.315983,...,0.078033,0.000000,0.531487,0.425893,0.357342,0.0,0.0,0.776956,0.085345,0.315983
75%,0.406897,1.000000,0.651163,0.583333,0.511719,0.751232,0.343731,0.365510,0.598780,0.513959,...,0.181567,0.000000,0.710821,0.511719,0.588111,0.0,0.0,0.876325,0.256681,0.513959
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.000000

In [ ]:
customer_agg[numeric_cols].describe()

,Age,Gender,NatureScore,CultureScore,AdventureScore,SpiritualScore,BookingLeadDays,DurationDays,FamilySize,InternetSpeedMbps,...,avg_booking_value_inr,international_trip_ratio,luxury_hotel_ratio,budget_booking_ratio,price_sensitivity_score,weekend_trip_ratio,last_minute_search_ratio,cancellation_rate,loyalty_points_balance,mobile_booking_ratio
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,...,30.000000,30.000000,30.000000,30.000000,30.000000,30.0,30.0,30.000000,30.000000,30.000000
mean,0.353793,0.450000,0.468365,0.451214,0.410347,0.582718,0.237128,0.265149,0.455837,0.342363,...,0.180445,0.033333,0.534344,0.410347,0.435831,0.0,0.0,0.682644,0.188927,0.342363
std,0.386089,0.422431,0.262587,0.255834,0.232711,0.231267,0.225567,0.234662,0.266324,0.252111,...,0.245217,0.182574,0.259380,0.232711,0.264880,0.0,0.0,0.274004,0.226414,0.252111
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.312016,0.283333,0.299107,0.451970,0.055244,0.102882,0.278963,0.113943,...,0.037692,0.000000,0.365643,0.299107,0.266254,0.0,0.0,0.453785,0.045833,0.113943
50%,0.217241,0.500000,0.454780,0.408889,0.425893,0.566502,0.203132,0.150398,0.402439,0.315983,...,0.078033,0.000000,0.531487,0.425893,0.357342,0.0,0.0,0.776956,0.085345,0.315983
75%,0.406897,1.000000,0.651163,0.583333,0.511719,0.751232,0.343731,0.365510,0.598780,0.513959,...,0.181567,0.000000,0.710821,0.511719,0.588111,0.0,0.0,0.876325,0.256681,0.513959
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.000000

In [ ]:
import numpy as np
np.random.seed(42)
customer_agg['target_booking'] = np.random.choice([0,1], size=len(customer_agg), p=[0.3,0.7])
customer_agg['target_response'] = np.random.choice([0,1], size=len(customer_agg), p=[0.4,0.6])

In [ ]:
augmented_data=customer_agg.copy()

In [ ]:
numeric_cols = [
    'Age',
    'Gender',
    'NatureScore',
    'CultureScore',
    'AdventureScore',
    'SpiritualScore',
    'BookingLeadDays',
    'DurationDays',
    'FamilySize',
    'InternetSpeedMbps',
    'NetworkQuality',
    'PermitsRequired',
    'destination_diversity',
    'category_diversity',
    'trip_frequency_per_year',
    'adventure_pref_score',
    'culture_pref_score',
    'nature_pref_score',
    'spiritual_pref_score',
    'engagement_score',
    'avg_booking_value_inr',
    'international_trip_ratio',
    'luxury_hotel_ratio',
    'budget_booking_ratio',
    'price_sensitivity_score',
    'weekend_trip_ratio',
    'last_minute_search_ratio',
    'cancellation_rate',
    'loyalty_points_balance',
    'mobile_booking_ratio'
]


np.random.seed(42)
noise_factor=0.05
synthetic_rows=augmented_data.copy()
for col in numeric_cols:
    noise = np.random.normal(0, noise_factor, size=len(synthetic_rows))
    synthetic_rows[col] = synthetic_rows[col] * (1 + noise)
synthetic_rows[numeric_cols] = synthetic_rows[numeric_cols].clip(0, 1)

In [ ]:
augmented_data = pd.concat([augmented_data, synthetic_rows], ignore_index=True)
print("Original rows:", len(customer_agg))
print("Augmented rows:", len(augmented_data))

Original rows: 30
Augmented rows: 60

In [ ]:
augmented_data = augmented_data.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
customer_agg.to_csv('augmented_data.csv', index=False)
from google.colab import files
files.download('augmented_data.csv')